name: Test

on: push

jobs:
  test:
    name: Install
    runs-on: macos-14
    steps:
      - name: Install dotfiles
        run: curl https://raw.githubusercontent.com/osinga/dotfiles/main/src/install.sh | sh
